SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[ReleasedZip](
	[ZipID] [int] IDENTITY(1,1) NOT NULL,
	[Zip] [int] NOT NULL,
	[BeginDate] [datetime] NULL,
	[SunsetDate] [datetime] NULL,
 CONSTRAINT [pk_releasedZip_pid] PRIMARY KEY CLUSTERED 
(
	[ZipID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]