SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[StatusHistory](
	[StatusHistoryID] [int] IDENTITY(1,1) NOT NULL,
	[StatusID] [int] NOT NULL,
	[FileOrder] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[BoundaryFileID] [int] NOT NULL,
 CONSTRAINT [pk_StatusHistory_pid] PRIMARY KEY CLUSTERED 
(
	[StatusHistoryID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]